Typescript Integrations (components)
devacran/productive-list-app pull request #2
Opened 2020-11-19 00:28 UTC by devacran

2020-11-19 15:53 UTC, Juanantogg requested changes

2020-11-19 15:53 UTC, Juanantogg commented on package.json
> +    "@types/react-dom": "^16.9.9",
Todas las dependencias que agregues de `@types` deben de ir en `devDependencies` por que estas construyendo un Front, si estuvieras haciendo una librería si estarían bien aquí

2020-11-19 15:53 UTC, Juanantogg commented on src/App.js
> -
Siempre hay que procurar dejar un espacio al final de los `imports`

2020-11-19 15:53 UTC, Juanantogg commented on src/components/Header.tsx
> +import * as React from "react";
Creo que como lo tenias antes estaba bien

2020-11-19 15:53 UTC, Juanantogg commented on src/components/Header.tsx
> +type props = {
Los nombres de los tipos, interfaces y clases es mejor iniciarlas con Mayúscula y creo que se les podría dar un nombre mas descriptivo

```javascript
type HeaderProps = {
```

2020-11-19 15:53 UTC, Juanantogg commented on src/components/Header.tsx
> +  handleOpenStatsModal: (bol: Boolean) => void;
El tipo correcto para booleanos es `boolean`, recomiendo usar nombres de variables que den un poco mas de contexto para que el código sea mas fácil de leer

```javascript
handleOpenStatsModal: (value: boolean) => void;
```

2020-11-19 15:53 UTC, Juanantogg commented on src/components/Header.tsx
> +const Header = (props: props) => {
La forma correcta para declarar un componente se usar el tipo `FC` que proporciona `react`, para el caso que sea un componente que no recibe `props`

```javascript
const Header: FC = (props) => {
```

con props:

```javascript
const Header: FC<HeaderProps> = (props) => {
```

2020-11-19 15:53 UTC, Juanantogg commented on src/components/Header.tsx
> +  const { handleOpenStatsModal } = props;
Creo que es mas fácil si desde el inicio destructuras las `props` al menos en este caso te evita una linea

```javascript
onst Header: FC<Props> = ({ handleOpenStatsModal }) => {
```

2020-11-19 15:53 UTC, Juanantogg commented on src/components/ItemDescription.tsx
> +import { useState, useEffect } from "react";
Tienes imports repetidos

2020-11-19 15:53 UTC, Juanantogg commented on src/components/ItemDescription.tsx
> +const ItemDescription = ({ description, setDescription }: props) => {
En general recomiendo dejar saltos de linea entre bloques de código para que sea más legible

```ts
import React, { FC, useState, useEffect } from "react";
import { TextField } from "@material-ui/core";

type ItemDescriptionProps = {
  description: String;
  setDescription: (description: String) => void;
};

const ItemDescription: FC<ItemDescriptionProps> = ({ description, setDescription }) => {
  const [expand, setExpand] = useState(false);
  
  const handleClick = () => {
    setExpand(true);
  };
  
  useEffect(() => {
    description !== "" && setExpand(true);
  }, [description]);
  
  return (
    <div className="item__description">
      {!expand && <button onClick={handleClick}>+Añadir una nota</button>}
      {expand && (
        <TextField
          id="filled-multiline-static"
          label="Inserta una nota"
          multiline
          rows={4}
          defaultValue={description}
          onChange={evn => setDescription(evn.target.value)}
          variant="filled"
        />
      )}
    </div>
  );
};

export default ItemDescription;

```

2020-11-19 15:53 UTC, Juanantogg commented on src/types/index.ts
> +}
Recomiendo usar `snake case` en los `enum`

```ts
export enum TimerStatusTypes {
  IDLE = "IDLE",
  STOP = "STOP",
  PAUSE = "PAUSE",
  CONTINUE = "CONTINUE",
  IN_PROGRESS = "IN_PROGRESS"
}
```

2020-11-19 15:58 UTC, Juanantogg commented
Te recomiendo darle una revisada a `Prettier`, `Husky`, 'Lint staged` y `esLint` para que te ayuden con el formateo del código y con mejores practicas, puedes revisar como estan implementados en los repos que te paso Sloth, e igual si tienes dudas lo revisamos

2020-11-19 16:31 UTC, devacran commented on package.json
> +    "@types/react-dom": "^16.9.9",
Entendido y corrigiendo :+1:

2020-11-19 16:32 UTC, devacran commented on src/App.js
> -
Entendido y corrigiendo :+1:

2020-11-19 16:49 UTC, devacran commented on src/components/Header.tsx
> +  handleOpenStatsModal: (bol: Boolean) => void;
Entendido y corrigiendo :+1:

2020-11-19 17:08 UTC, devacran commented on src/components/Header.tsx
> +import * as React from "react";
Entendido y corrigiendo :+1:

2020-11-19 17:09 UTC, devacran commented on src/components/Header.tsx
> +  handleOpenStatsModal: (bol: Boolean) => void;
Entendido y corrigiendo :+1:

2020-11-19 17:10 UTC, devacran commented on src/App.js
> -
Entendido y corrigiendo :+1:

2020-11-19 17:10 UTC, devacran commented on src/components/ItemDescription.tsx
> +import { useState, useEffect } from "react";
Entendido y corrigiendo :+1:

2020-11-19 17:24 UTC, devacran commented on package.json
> +    "@types/react-dom": "^16.9.9",
Entendido y corrigiendo :+1:

2020-11-19 17:24 UTC, devacran commented on src/components/ItemDescription.tsx
> +const ItemDescription = ({ description, setDescription }: props) => {
Entendido y corrigiendo :+1:

2020-11-20 01:35 UTC, Juanantogg commented
Obtengo este error al levantar el proyecto
![Screenshot_20201119_193345](https://user-images.githubusercontent.com/41706582/99744918-33f7a880-2a9e-11eb-9132-abd72f89940d.png)

2020-11-20 15:04 UTC, devacran commented
> Obtengo este error al levantar el proyecto
> ![Screenshot_20201119_193345](https://user-images.githubusercontent.com/41706582/99744918-33f7a880-2a9e-11eb-9132-abd72f89940d.png)



> Obtengo este error al levantar el proyecto
> ![Screenshot_20201119_193345](https://user-images.githubusercontent.com/41706582/99744918-33f7a880-2a9e-11eb-9132-abd72f89940d.png)

Intenta clonar el repositorio nuevamente e instalarlo, parece que es un problema de yarn. Porque a mi no me sale ningun error.

2020-11-23 17:55 UTC, Juanantogg approved these changes

2020-11-23 17:55 UTC, Juanantogg commented on src/components/ItemDescription.tsx
> +}: ItemDescriptionProps) => {
Agregando `FC` o `FC<Props>`, ya no es necesario tipar los parametros que se reciben

```ts
const ItemDescription: FC<ItemDescriptionProps> = ({
  description,
  setDescription
}) => {
```

2020-11-23 17:58 UTC, Juanantogg commented
Va quedando bien, creo que quedaría mejor si estructuras los componentes en carpetas, y para cada componente agregas su archivo de estilos y de tipos correspondientes

2020-11-23 17:59 UTC, merged